add_rules("mode.debug", "mode.release")
set_languages("cxx17")
set_targetdir("build_standalone")
add_includedirs("deps/include")

-- Bundled MuJoCo 2.3.2 (headers + .so)
add_linkdirs("deps/lib")

add_requires("yaml-cpp 0.8.0")
add_requires("eigen 3.4.0")
add_requires("glfw3")

-- =========================================================================
-- Core libraries (static, zero middleware)
-- =========================================================================

target("quadrotor_sim")
set_kind("static")
add_files("core/quadrotor_sim/src/se3_controller.cpp")
add_includedirs("core/quadrotor_sim/include")
add_packages("eigen", "yaml-cpp")

target("quadrotor_sim_shm")
set_kind("static")
add_files("core/shm/src/shm_backend.cpp")
add_includedirs("core/shm/include", "core/quadrotor_sim/include")
add_deps("quadrotor_sim")
add_syslinks("pthread", "rt", "dl")

target("quadrotor_sim_mujoco")
set_kind("static")
add_files("core/mujoco/src/sim_core.cpp")
add_includedirs("core/mujoco/include", "core/shm/include", "core/quadrotor_sim/include")
add_deps("quadrotor_sim", "quadrotor_sim_shm")
add_links("mujoco")
add_syslinks("pthread", "rt", "dl")

target("quadrotor_sim_core")
set_kind("binary")
add_files("apps/sim_core.cpp")
add_includedirs("core/mujoco/include", "core/quadrotor_sim/include")
add_deps("quadrotor_sim_mujoco")
add_syslinks("pthread", "rt", "dl")

target("quadrotor_sim_render")
set_kind("static")
add_files("core/mujoco/src/render.cpp")
add_includedirs("core/mujoco/include", "core/quadrotor_sim/include")
add_deps("quadrotor_sim")
add_links("mujoco")
add_syslinks("pthread", "rt", "dl")

target("quadrotor_sim_glfw_viewer")
set_kind("static")
add_files("core/glfw/src/viewer.cpp")
add_includedirs("core/glfw/include")
add_packages("glfw3")
add_links("mujoco", "GL")

target("quadrotor_sim_glfw_adapter")
    set_kind("binary")
    add_files("apps/sim_render.cpp")
    add_includedirs("core/shm/include", "core/quadrotor_sim/include")
    add_packages("glfw3")
    add_deps("quadrotor_sim_shm")
    add_links("mujoco")
    add_syslinks("pthread", "rt", "dl")

target("quadrotor_sim_se3_direct")
set_kind("binary")
add_files("apps/se3_direct.cpp")
add_includedirs("core/shm/include", "core/quadrotor_sim/include")
add_deps("quadrotor_sim", "quadrotor_sim_shm")
add_packages("yaml-cpp")
add_syslinks("pthread", "rt", "dl")
